Keeping the initial mouse mode when switching back to the character camera
bbbscarter/GodotRuntimeDebugTools pull request #5
Opened 2024-08-30 14:50 UTC by GonnaFlyMethod

Hey, the pull request  is related to this [issue](https://github.com/bbbscarter/GodotRuntimeDebugTools/issues/4).

_____

Description:
The enhancement is implemented via:

1. memorizing the initial mouse mode when entering the debug mode
2. setting the flag `_set_initial_mouse_mode` to `true` when we exiting from the Debugging mode.
3. tracking whether the game process is in focus or in background.
4. if `_set_initial_mouse_mode` is `true` and game process is in focus then we're setting initial mouse mode

Why we need to check out whether the game process is in focus or in background?
As for me, when running the game process in "windowed"  mode (Project settings -> Display -> Window -> Mode), switching back from RDT to character camera causes my mouse stuck in the frame dimensions of the game window, here's the showcase:

https://github.com/user-attachments/assets/2ffca708-353e-4f1d-8500-be93190f0fac

This happens, if the initial mouse mode of the game (before entering the debugging mode) has these values:

```
MOUSE_MODE_CAPTURED = 2
MOUSE_MODE_CONFINED = 3
MOUSE_MODE_CONFINED_HIDDEN 
```

To avoid this, I'm tracking whether the game process is actually in focus now.

2024-09-02 11:14 UTC, bbbscarter requested changes
Looks good - thanks for doing this!

Acouple of naming requests, and a suggestion that should hopefully remove a bunch of code.

2024-09-02 11:14 UTC, bbbscarter commented on addons/runtime_debug_tools/scripts/debug_runtime_interaction_2d.gd
> +var _initialMouseMode : Input.MouseMode
Request - rename this `_previous_mouse_mode`.

- The naming convention here is `_underscore_case`.
- A similar pattern is being followed for restoring cameras, where the naming is `_previous_camera`.

2024-09-02 11:14 UTC, bbbscarter commented on addons/runtime_debug_tools/scripts/debug_runtime_interaction_2d.gd
> +    if _is_game_process_in_focus and _set_initial_mouse_mode:
I think you can remove the manual focus checking you're doing here, and in `_notification`, and replace it with:

`get_window().has_focus()`

2024-09-02 11:14 UTC, bbbscarter commented on addons/runtime_debug_tools/scripts/debug_runtime_interaction_3d.gd
> +    if _is_game_process_in_focus and _set_initial_mouse_mode:
Same as in the 2d equivalent:

I think you can remove the manual focus checking you're doing here, and in `_notification`, and replace it with:

`get_window().has_focus()`

2024-09-02 11:14 UTC, bbbscarter commented on addons/runtime_debug_tools/scripts/debug_runtime_interaction_3d.gd
> +var _initialMouseMode : Input.MouseMode
(Same as in the 2D equivalent)
Request - rename this `_previous_mouse_mode`.

2024-09-02 11:14 UTC, bbbscarter commented on addons/runtime_debug_tools/scripts/debug_runtime_interaction_2d.gd
> +var _set_initial_mouse_mode : bool
Request - rename this to `_restore_previous_mouse_mode`

2024-09-02 11:14 UTC, bbbscarter commented on addons/runtime_debug_tools/scripts/debug_runtime_interaction_3d.gd
> +var _set_initial_mouse_mode : bool
(Same as 2D equivalent)

Request - rename this to `_restore_previous_mouse_mode`

2024-09-04 10:45 UTC, GonnaFlyMethod commented
hi, yeah, the suggestions looks reasonable, I'll take a look on them

2024-09-04 14:52 UTC, GonnaFlyMethod commented
Hi, thank you for the suggestions, I've modified the code accordingly👍

2024-09-05 11:00 UTC, merged

2024-09-05 11:01 UTC, bbbscarter commented
Great - I've merged this in.

Many thanks!

2024-09-05 11:04 UTC, GonnaFlyMethod commented
Hey, cool, thanks, I'll delete the branch then + I have some ideas regarding the project, do you have some kind of roadmap?

2024-09-05 16:22 UTC, bbbscarter commented
Nope, no roadmap - it's intended to be a fairly simple project. I'm mostly
just adding things based on what I find I'm missing.

Proper remappable in-game keybindings are next on my list.

On Thu, 5 Sept 2024 at 12:04, Aliaksandr Husakou ***@***.***>
wrote:

> Hey, cool, thanks, I'll delete the branch then + I have some ideas
> regarding the project, do you have some kind of roadmap?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bbbscarter/GodotRuntimeDebugTools/pull/5#issuecomment-2331237190>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHDB6ZKAQBHUHA6JRKFRDDZVA3FPAVCNFSM6AAAAABNMUJS4KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZRGIZTOMJZGA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>